service: flask-lambda-app
org: sergiocestd
app: sergio-cespedes-td-web
provider:
  name: aws
  runtime: python3.12
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
    packRequirements: false  # Cambia a false para manejar las dependencias manualmente

